# Generated by Django 5.2.9 on 2025-12-16 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model("registrar", "UserSecurityProfile")
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user, defaults={"must_change_password": True})


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSecurityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="登录后会被强制跳转到修改密码页面。",
                        verbose_name="首次登录需修改密码",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "账号安全设置",
                "verbose_name_plural": "账号安全设置",
            },
        ),
        migrations.RunPython(
            code=create_profiles,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
