# Generated by Django 5.2.9 on 2025-12-16 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0002_usersecurity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesection",
            name="grades_locked",
            field=models.BooleanField(default=False, verbose_name="成绩填报锁定"),
        ),
        migrations.CreateModel(
            name="StudentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("enroll", "报名/选课"),
                            ("drop", "退课申请"),
                            ("retake", "重修申请"),
                            ("waitlist", "容量候补"),
                            ("cross_college", "跨院选课审批"),
                            ("credit_overload", "超学分申请"),
                            ("waitlist_promotion", "候补转正审批"),
                        ],
                        max_length=32,
                        verbose_name="申请类型",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="申请原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="附加信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="registrar.coursesection",
                        verbose_name="教学班",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="registrar.studentprofile",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生自助申请",
                "verbose_name_plural": "学生自助申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "通过"), ("rejected", "驳回")],
                        max_length=16,
                        verbose_name="操作",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="审核意见")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="registrar.studentrequest",
                        verbose_name="申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批日志",
                "verbose_name_plural": "审批日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
