# Generated by Django 5.2.9 on 2025-12-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0003_coursesection_grades_locked_studentrequest_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "ordering": ["student_number", "user__username"],
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
            },
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="student_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="学号"
            ),
        ),
    ]
