# Generated by Django 5.2.9 on 2025-12-16 12:31

from django.db import migrations, models


def normalize_waitlist_records(apps, schema_editor):
    Enrollment = apps.get_model("registrar", "Enrollment")
    StudentRequest = apps.get_model("registrar", "StudentRequest")

    Enrollment.objects.filter(status="waitlisted").update(status="enrolling")
    StudentRequest.objects.filter(request_type__in=["waitlist", "waitlist_promotion"]).update(
        request_type="enroll"
    )


def noop_reverse(apps, schema_editor):
    """No-op reverse migration; legacy states are deprecated."""
    # Intentionally left blank.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0004_alter_studentprofile_options_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_waitlist_records, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("enrolling", "选课中"),
                    ("dropped", "已退课"),
                    ("passed", "已通过"),
                    ("failed", "未通过"),
                ],
                default="enrolling",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="studentrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("enroll", "报名/选课"),
                    ("drop", "退课申请"),
                    ("retake", "重修申请"),
                    ("cross_college", "跨院选课审批"),
                    ("credit_overload", "超学分申请"),
                ],
                max_length=32,
                verbose_name="申请类型",
            ),
        ),
    ]
