# Generated by Django 5.2.9 on 2025-12-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0005_alter_enrollment_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="college",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="registrar.department",
                verbose_name="学院",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="student_number",
            field=models.CharField(
                blank=True, max_length=32, null=True, unique=True, verbose_name="学号"
            ),
        ),
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="班级名称")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_groups",
                        to="registrar.department",
                        verbose_name="所属学院",
                    ),
                ),
            ],
            options={
                "verbose_name": "班级",
                "verbose_name_plural": "班级",
                "ordering": ["department__code", "name"],
                "unique_together": {("name", "department")},
            },
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="registrar.classgroup",
                verbose_name="班级",
            ),
        ),
    ]
