# Generated by Django 5.2.9 on 2025-12-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0006_remove_studentprofile_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="numeric_code",
            field=models.PositiveIntegerField(
                default=0, unique=True, verbose_name="院系编号"
            ),
        ),
    ]
