# Generated by Django 5.2.9 on 2025-12-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0007_department_numeric_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="方案名称")),
                ("major", models.CharField(max_length=255, verbose_name="面向专业")),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="适用年级/年份"),
                ),
                (
                    "enrollment_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="选课开始时间"
                    ),
                ),
                (
                    "enrollment_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="选课结束时间"
                    ),
                ),
                (
                    "total_credits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="建议总学分",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_plans",
                        to="registrar.department",
                        verbose_name="学院",
                    ),
                ),
            ],
            options={
                "verbose_name": "人才培养方案",
                "verbose_name_plural": "人才培养方案",
                "ordering": ["-academic_year", "department__code", "major"],
            },
        ),
        migrations.CreateModel(
            name="ProgramRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general_required", "通识必修"),
                            ("major_required", "专业必修"),
                            ("major_elective", "专业选修"),
                            ("university_elective", "校级选修"),
                            ("practical", "实践/实验"),
                        ],
                        max_length=50,
                        verbose_name="课程类别",
                    ),
                ),
                (
                    "required_credits",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="建议修读学分"
                    ),
                ),
                (
                    "recommended_term",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="建议学期/年级"
                    ),
                ),
                (
                    "selection_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="选课开始时间"
                    ),
                ),
                (
                    "selection_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="选课结束时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="program_requirements",
                        to="registrar.course",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="registrar.programplan",
                        verbose_name="所属方案",
                    ),
                ),
            ],
            options={
                "verbose_name": "培养方案要求",
                "verbose_name_plural": "培养方案要求",
                "ordering": ["plan", "category", "recommended_term"],
            },
        ),
    ]
