# Generated by Django 5.2.9 on 2025-12-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0008_programplan_programrequirement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesection",
            name="section_number",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="教学班号"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="final_grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="最终成绩",
            ),
        ),
    ]
