# Generated by Django 5.2.9 on 2025-12-17

from django.db import migrations


def forward(apps, schema_editor):
    Course = apps.get_model("registrar", "Course")
    ProgramRequirement = apps.get_model("registrar", "ProgramRequirement")

    mapping = {
        "general_required": "foundational_required",
        "university_elective": "general_elective",
        "major_required": "major_required",
        "major_elective": "major_elective",
        "practical": "practical",
    }
    for course in Course.objects.all():
        new_value = mapping.get(course.course_type, course.course_type)
        course.course_type = new_value
        course.save(update_fields=["course_type"])

    for req in ProgramRequirement.objects.all():
        new_value = mapping.get(req.category, req.category)
        req.category = new_value
        req.save(update_fields=["category"])


def backward(apps, schema_editor):
    Course = apps.get_model("registrar", "Course")
    ProgramRequirement = apps.get_model("registrar", "ProgramRequirement")

    reverse_mapping = {
        "foundational_required": "general_required",
        "general_elective": "university_elective",
    }
    for course in Course.objects.all():
        course.course_type = reverse_mapping.get(course.course_type, course.course_type)
        course.save(update_fields=["course_type"])

    for req in ProgramRequirement.objects.all():
        req.category = reverse_mapping.get(req.category, req.category)
        req.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0009_alter_coursesection_section_number_and_more"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]

