# Generated by Django 5.2.9 on 2025-12-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0010_update_course_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("foundational_required", "基础必修"),
                    ("general_elective", "全校通识课"),
                    ("major_required", "专业必修"),
                    ("major_elective", "专业选修"),
                    ("practical", "实践课"),
                    ("lab", "实验课"),
                ],
                max_length=50,
                verbose_name="课程类别",
            ),
        ),
        migrations.AlterField(
            model_name="programrequirement",
            name="category",
            field=models.CharField(
                choices=[
                    ("foundational_required", "基础必修"),
                    ("general_elective", "全校通识课"),
                    ("major_required", "专业必修"),
                    ("major_elective", "专业选修"),
                    ("practical", "实践课"),
                    ("lab", "实验课"),
                ],
                max_length=50,
                verbose_name="课程类别",
            ),
        ),
    ]
