# Generated by Django 5.2.9 on 2025-12-17 13:32

import datetime

from django.db import migrations, models
from django.db.models import Max


def populate_student_numbers(apps, schema_editor):
    StudentProfile = apps.get_model("registrar", "StudentProfile")
    Department = apps.get_model("registrar", "Department")

    def ensure_numeric_code(department):
        if department.numeric_code is None:
            current_max = Department.objects.aggregate(max_code=Max("numeric_code")).get("max_code") or 0
            department.numeric_code = current_max + 1
            department.save(update_fields=["numeric_code"])
        return department.numeric_code or 0

    for student in StudentProfile.objects.filter(models.Q(student_number__isnull=True) | models.Q(student_number="")):
        dept_code = "000"
        if student.department_id:
            code_value = ensure_numeric_code(student.department)
            dept_code = f"{int(code_value):03d}"

        year_prefix = datetime.date.today().year
        base_prefix = f"{year_prefix}{dept_code}"
        last_number = (
            StudentProfile.objects.filter(student_number__startswith=base_prefix)
            .exclude(models.Q(student_number__isnull=True) | models.Q(student_number=""))
            .order_by("-student_number")
            .values_list("student_number", flat=True)
            .first()
        )
        sequence = int(last_number[-3:]) + 1 if last_number and last_number[-3:].isdigit() else 1
        student.student_number = f"{base_prefix}{sequence:03d}"
        student.save(update_fields=["student_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0011_alter_course_course_type_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_student_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="studentprofile",
            name="student_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, unique=True, verbose_name="学号"
            ),
        ),
    ]
